os: 
  editCommand: 'floaterm'
  edit: 'nvim {{filename}}'
  # editAtLine: 'nvim --line={{line}} {{filename}}'
  editAtLine: 'nvim {{filename}} +{{line}}'
  editAtLineAndWait: 'nvim --block --line={{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim {{dir}}'
gui:
  # sidePanelWidth: 0.2 
  # gives you more space to show things side-by-side
  # Fraction of the total screen width to use for the left side section. You may want to pick a small number (e.g. 0.2) if you're using a narrow screen, so that you can see more of the main section.
  # Number from 0 to 1.0.
  sidePanelWidth: 0.2
   # Whether to split the main window when viewing file changes.
  # One of: 'auto' | 'always'
  # If 'auto', only split the main window when a file has both staged and unstaged changes
  splitDiff: auto
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: double
  theme:
    activeBorderColor:
      - "#94e2d5"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#94e2d5"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
git:
  paging:
    colorArg: always
    # useConfig: false
    pager: delta --dark --paging=never
    # pager: delta --dark --paging=never --show-syntax-themes 
  commitPrefixes:
      tridentity-be: # This is repository folder name
        pattern: "^\\w+\\/(\\w+-\\w+).*"
        replace: '[$1] '
